# Generated by Django 5.1.6 on 2025-03-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
