# Generated by Django 5.1.6 on 2025-04-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0005_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.color'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.product'),
        ),
        migrations.AddField(
            model_name='productuser',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.product'),
        ),
        migrations.AddField(
            model_name='productuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super.client'),
        ),
    ]
